language: csharp

os:
  - osx

# Ubuntu 14.04
sudo: required
dist: trusty

# macOS 10.14
osx_image: xcode11

mono:
  - 5.20.1

dotnet: 2.1.101
  
script:
  - ./build.sh --verbosity diagnostic

cache:

  directories:
  - .cake/tools